Need to add "name" into the output definition
I've got this error when running ./execute.py using the actor output
definition from the documentation.

Traceback (most recent call last):
File "execute.py", line 24, in <module>
main()
File "execute.py", line 14, in main
load(actors_dir)
File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 86, in load
_load(os.path.basename(root), os.path.join(root, '_actor.yaml'), tags, post_resolve)
File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 39, in _load
create_actor(name, d)
File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 49, in create_actor
register_actor(name, Definition(name, definition), executor)
File "/usr/lib/python2.7/site-packages/snactor/definition.py", line 33, in __init__
self.__resolve_channel_type(self.outputs)
File "/usr/lib/python2.7/site-packages/snactor/definition.py", line 20, in __resolve_channel_type
channel["type"].setdefault("version", LATEST)
AttributeError: 'str' object has no attribute 'setdefault'